name: pybosse
channels:
    - conda-forge
dependencies:
    - python=3.11
    - dask
    - h5netcdf
    - joblib
    - jupyter
    - matplotlib
    - netCDF4
    - notebook
    - numpy
    - pandas=2.1.1
    - pyet
    - python-wget
    - scipy
    - scikit-learn=1.3.1
    - scikit-image
    - seaborn
    - regex
    - shapely
    - pickledb
    - pip
    - xarray
    - pip:
        - python-rle
        - nlmpy
        - git+https://github.com/JavierPachecoLabrador/pyGNDiv-master